### ISSUE TITLE
Broken map.

### ISSUE THREAD

**Issue by slopjong** [trevorpower/hackerspaces-status-wall#10]
## The problem

The broken map is due to, uhm, [cloudmade shutting down the free plan](http://notes.ericjiang.com/posts/741). All the requests are blocked.

![cloudmade](https://cloud.githubusercontent.com/assets/456443/3110094/6290b86e-e6a1-11e3-888a-bfc51a2755d2.png)
## Alternatives
- OpenStreetMap
- [https://www.mapbox.com/plans/](mapbox.com)
- what else?

**Comment by trevorpower** [comment]
Switched to mapbox free account for now.
