### ISSUE TITLE
db does not update when existing hackspace gets new API

### ISSUE THREAD

**Issue by eins78** [trevorpower/hackerspaces-status-wall#2]
api.maschinenraum.tk is missing from hackerspaces.me.
i lurked into the code a little and my guess would be that since the space had no API when it got created in zour db, it is not marked as "no api". it does not seem to update this info when an "old" space gets announced by OpenSpaceDirectory.

**Comment by trevorpower** [comment]
The space API should be in the directory by now.

The database is synced periodically with the directory (normally every day) but triggered manually at the moment so it wasn't done over Christmas.

I'm working on triggering it automatically as I write this.

**Comment by trevorpower** [comment]
The database is now automatically synced with the directory twice a day.
