### ISSUE TITLE
Where is foreman (or in what package is it) on an Ubuntu 12.04 system?

### ISSUE THREAD

**Issue by slopjong** [trevorpower/hackerspaces-status-wall#8]
I've prepared a Vagrant box for easier local development. Unfortunately I'm not able to get foreman run.

From this [list](http://theforeman.org/manuals/1.5/index.html#3.3.3DebianPackages) I've installed the following packages:
- foreman
- foreman-cli
- foreman-console
- foreman-gce
- ruby-hammer-cli-foreman
- ruby-hammer-cli

@trevorpower can you make the Vagrant box work?
## Vagrant

For the case you don't know Vagrant, install it on your system (beside VirtualBox) and change to the project directory. Here you simply execute `vagrant up` and ssh into it with `vagrant ssh`.

Inside the box the shared folder is mounted to `/vagrant`.

The vagrant files are in the `feature/vagrant-box` branch while foreman is configured [here](https://github.com/trevorpower/hackerspaces-status-wall/blob/feature/vagrant-box/data/vm/cookbooks/foreman/recipes/default.rb).

**Comment by trevorpower** [comment]
I won't get a chance to look into this until next week, looking after new born baby at the moment :)

As for foreman, of the top of my head , `$ gem install foreman`.

**Comment by slopjong** [comment]
Installing `foreman` through `gem_package`.
